@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
REM ==========================================================================
REM AeroOne Leantime co-deploy stack — first-time SETUP (portable PHP+MariaDB).
REM Ships INSIDE the separate Leantime stack import (AeroOne-Leantime-Stack-*.zip),
REM so %~dp0 is the stack root with php\ mariadb\ leantime\ as siblings.
REM
REM What it does (idempotent where possible):
REM   1) generate php\php.ini with the deployment-time extension_dir
REM   2) initialize the portable MariaDB data dir (once)
REM   3) start MariaDB (loopback, port %LEANTIME_DB_PORT%, default 3307)
REM   4) create the leantime database + scoped user
REM   5) run Leantime db:migrate non-interactively (schema + first admin)
REM Run start-leantime-stack.bat afterwards for day-to-day boot.
REM ==========================================================================

set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
if not defined LEANTIME_DB_PORT set "LEANTIME_DB_PORT=3307"
if not defined LEANTIME_PORT set "LEANTIME_PORT=8081"
if not defined LEANTIME_DB_PASSWORD set "LEANTIME_DB_PASSWORD=lean_local_pw"
if not defined LEANTIME_ADMIN_EMAIL set "LEANTIME_ADMIN_EMAIL=admin@aeroone.local"
if not defined LEANTIME_ADMIN_PASSWORD set "LEANTIME_ADMIN_PASSWORD=AeroOneLean2026!"

set "PHP=%ROOT%\php\php.exe"
set "PHPINI=%ROOT%\php\php.ini"
set "MARIADB=%ROOT%\mariadb\bin"
set "DATA=%ROOT%\data"

for %%P in ("%PHP%" "%MARIADB%\mariadbd.exe" "%ROOT%\leantime\bin\leantime") do (
  if not exist "%%~P" (
    echo [LEANTIME][ERROR] missing stack component: %%~P
    echo [LEANTIME][ERROR] the stack was not assembled correctly. Re-import AeroOne-Leantime-Stack-*.zip.
    exit /b 1
  )
)

echo [LEANTIME][INFO ] writing php.ini (extension_dir = %ROOT%\php\ext)
> "%PHPINI%" echo ; AeroOne Leantime stack PHP config (generated by setup-leantime-stack.bat)
>>"%PHPINI%" echo extension_dir = "%ROOT%\php\ext"
for %%E in (curl exif fileinfo gd gettext intl ldap mbstring mysqli openssl pdo_mysql soap sodium zip) do >>"%PHPINI%" echo extension=%%E
>>"%PHPINI%" echo zend_extension=opcache
>>"%PHPINI%" echo memory_limit = 512M
>>"%PHPINI%" echo max_execution_time = 300
>>"%PHPINI%" echo upload_max_filesize = 64M
>>"%PHPINI%" echo post_max_size = 64M
>>"%PHPINI%" echo date.timezone = Asia/Seoul
>>"%PHPINI%" echo opcache.enable = 1
>>"%PHPINI%" echo opcache.enable_cli = 0

if not exist "%DATA%\mysql" (
  echo [LEANTIME][INFO ] initializing MariaDB data dir ...
  "%MARIADB%\mariadb-install-db.exe" --datadir="%DATA%" >nul 2>&1
  if errorlevel 1 (
    echo [LEANTIME][ERROR] MariaDB data dir init failed.
    exit /b 1
  )
) else (
  echo [LEANTIME][INFO ] MariaDB data dir already initialized (skip).
)

echo [LEANTIME][INFO ] starting MariaDB on 127.0.0.1:%LEANTIME_DB_PORT% ...
start "aeroone-leantime-mariadbd" "%MARIADB%\mariadbd.exe" --datadir="%DATA%" --port=%LEANTIME_DB_PORT% --skip-name-resolve --bind-address=127.0.0.1
call :wait_tcp %LEANTIME_DB_PORT% 30
if errorlevel 1 (
  echo [LEANTIME][ERROR] MariaDB did not start within 30s.
  exit /b 1
)

echo [LEANTIME][INFO ] creating database + scoped user ...
set "SQLTMP=%TEMP%\aeroone_leantime_init_%RANDOM%.sql"
> "%SQLTMP%" echo CREATE DATABASE IF NOT EXISTS leantime CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
>>"%SQLTMP%" echo CREATE USER IF NOT EXISTS 'leantime'@'127.0.0.1' IDENTIFIED BY '%LEANTIME_DB_PASSWORD%';
>>"%SQLTMP%" echo CREATE USER IF NOT EXISTS 'leantime'@'localhost' IDENTIFIED BY '%LEANTIME_DB_PASSWORD%';
>>"%SQLTMP%" echo GRANT ALL PRIVILEGES ON leantime.* TO 'leantime'@'127.0.0.1';
>>"%SQLTMP%" echo GRANT ALL PRIVILEGES ON leantime.* TO 'leantime'@'localhost';
>>"%SQLTMP%" echo FLUSH PRIVILEGES;
"%MARIADB%\mariadb.exe" -u root --host=127.0.0.1 --port=%LEANTIME_DB_PORT% < "%SQLTMP%" >nul 2>&1
del /q "%SQLTMP%" >nul 2>&1

echo [LEANTIME][INFO ] installing Leantime schema + first admin (non-interactive) ...
set "LEAN_DB_HOST=127.0.0.1"
set "LEAN_DB_USER=leantime"
set "LEAN_DB_PASSWORD=%LEANTIME_DB_PASSWORD%"
set "LEAN_DB_DATABASE=leantime"
set "LEAN_DB_PORT=%LEANTIME_DB_PORT%"
set "LEAN_USE_REDIS=false"
set "LEAN_NEWS_ENABLED=false"
set "LEAN_APP_URL=http://localhost:%LEANTIME_PORT%"
pushd "%ROOT%\leantime"
"%PHP%" -c "%PHPINI%" bin\leantime db:migrate -n --email=%LEANTIME_ADMIN_EMAIL% --password=%LEANTIME_ADMIN_PASSWORD% --company-name=AeroOne --first-name=Admin --last-name=User
set "LT_INSTALL_EXIT=%errorlevel%"
popd
if not "%LT_INSTALL_EXIT%"=="0" (
  echo [LEANTIME][WARN ] db:migrate returned %LT_INSTALL_EXIT%. If tables exist this may be a re-run; verify with start-leantime-stack.bat.
)

echo [LEANTIME][READY] setup complete. Admin: %LEANTIME_ADMIN_EMAIL%
echo [LEANTIME][INFO ] next: start-leantime-stack.bat  (serves http://localhost:%LEANTIME_PORT%)
exit /b 0

:wait_tcp
REM %1 port, %2 timeout seconds
set "WT_PORT=%~1"
powershell -NoLogo -NoProfile -Command "$p=%WT_PORT%;$t=%~2;for($i=0;$i -lt $t;$i++){try{$c=New-Object Net.Sockets.TcpClient;$c.Connect('127.0.0.1',$p);$c.Close();exit 0}catch{Start-Sleep 1}};exit 1"
exit /b %errorlevel%
