@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul
REM Delayed expansion stays OFF: passwords/values may contain '!' and cmd would
REM silently strip it (documented default admin password ends with '!').
REM ==========================================================================
REM AeroOne Leantime co-deploy stack — first-time SETUP (portable PHP+MariaDB).
REM Ships INSIDE the separate Leantime stack import (AeroOne-Leantime-Stack-*.zip),
REM so %~dp0 is the stack root with php\ mariadb\ leantime\ as siblings.
REM
REM What it does (idempotent where possible):
REM   1) generate php\php.ini with the deployment-time extension_dir
REM   2) initialize the portable MariaDB data dir (once)
REM   3) start MariaDB (loopback, port %LEANTIME_DB_PORT%, default 3307)
REM   4) create the leantime database + scoped user
REM   5) run Leantime db:migrate non-interactively (schema + first admin)
REM Run start-leantime-stack.bat afterwards for day-to-day boot.
REM ==========================================================================

REM 더블클릭(탐색기) 실행 감지 — 오류/완료 시 창이 즉시 닫히지 않게 pause 한다.
REM 자동화에서 pause 를 막으려면 AEROONE_LT_NO_PAUSE=1 을 설정한다.
set "AEROONE_LT_INTERACTIVE="
echo "%cmdcmdline%" | find /i "%~nx0" >nul && set "AEROONE_LT_INTERACTIVE=1"
if defined AEROONE_LT_NO_PAUSE set "AEROONE_LT_INTERACTIVE="

set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
if not defined LEANTIME_DB_PORT set "LEANTIME_DB_PORT=3307"
if not defined LEANTIME_PORT set "LEANTIME_PORT=8081"
REM 초기 env: 자격증명은 이 스택 폴더의 leantime.env 에서 로드하고(재실행 멱등), env/파일에
REM 없으면 설치마다 강random 으로 생성한다. 하드코딩 공용 비밀번호를 쓰지 않는다.
REM 우선순위: 이미 설정된 프로세스 env(AeroOne 초기 env·운영자 오버라이드) > leantime.env > 신규 생성.
set "LEANTIME_ENV_FILE=%ROOT%\leantime.env"
if exist "%LEANTIME_ENV_FILE%" for /f "usebackq eol=# tokens=1,* delims==" %%A in ("%LEANTIME_ENV_FILE%") do if not defined %%A set "%%A=%%B"
if not defined LEANTIME_ADMIN_EMAIL set "LEANTIME_ADMIN_EMAIL=admin@aeroone.local"
if not defined LEANTIME_DB_PASSWORD for /f "delims=" %%S in ('powershell -NoLogo -NoProfile -Command "$b=[byte[]]::new(18);$r=[Security.Cryptography.RandomNumberGenerator]::Create();try{$r.GetBytes($b)}finally{$r.Dispose()};[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()"') do set "LEANTIME_DB_PASSWORD=%%S"
if not defined LEANTIME_ADMIN_PASSWORD for /f "delims=" %%S in ('powershell -NoLogo -NoProfile -Command "$b=[byte[]]::new(18);$r=[Security.Cryptography.RandomNumberGenerator]::Create();try{$r.GetBytes($b)}finally{$r.Dispose()};[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()"') do set "LEANTIME_ADMIN_PASSWORD=%%SAa1!"
REM 확정된 자격증명을 초기 env 파일로 영속화한다(start-leantime-stack.bat 이 같은 값을 읽는다).
REM 이 파일은 반출·공유·커밋 금지. 재생성하려면 파일을 지우고 setup 을 다시 실행한다.
> "%LEANTIME_ENV_FILE%" echo # AeroOne Leantime stack initial env - do NOT share/commit. Delete this file and re-run setup to regenerate.
>>"%LEANTIME_ENV_FILE%" echo LEANTIME_ADMIN_EMAIL=%LEANTIME_ADMIN_EMAIL%
>>"%LEANTIME_ENV_FILE%" echo LEANTIME_ADMIN_PASSWORD=%LEANTIME_ADMIN_PASSWORD%
>>"%LEANTIME_ENV_FILE%" echo LEANTIME_DB_PASSWORD=%LEANTIME_DB_PASSWORD%
>>"%LEANTIME_ENV_FILE%" echo LEANTIME_PORT=%LEANTIME_PORT%
>>"%LEANTIME_ENV_FILE%" echo LEANTIME_DB_PORT=%LEANTIME_DB_PORT%

set "PHP=%ROOT%\php\php.exe"
set "PHPINI=%ROOT%\php\php.ini"
set "MARIADB=%ROOT%\mariadb\bin"
set "DATA=%ROOT%\data"

for %%P in ("%PHP%" "%MARIADB%\mariadbd.exe" "%ROOT%\leantime\bin\leantime") do (
  if not exist "%%~P" (
    echo [LEANTIME][ERROR] missing stack component: %%~P
    echo [LEANTIME][ERROR] the stack was not assembled correctly. Re-import AeroOne-Leantime-Stack-*.zip.
    goto :fail
  )
)

echo [LEANTIME][INFO ] writing php.ini (extension_dir = %ROOT%\php\ext)
> "%PHPINI%" echo ; AeroOne Leantime stack PHP config (generated by setup-leantime-stack.bat)
>>"%PHPINI%" echo extension_dir = "%ROOT%\php\ext"
for %%E in (curl exif fileinfo gd gettext intl ldap mbstring mysqli openssl pdo_mysql soap sodium zip) do >>"%PHPINI%" echo extension=%%E
>>"%PHPINI%" echo zend_extension=opcache
>>"%PHPINI%" echo memory_limit = 512M
>>"%PHPINI%" echo max_execution_time = 300
>>"%PHPINI%" echo upload_max_filesize = 64M
>>"%PHPINI%" echo post_max_size = 64M
>>"%PHPINI%" echo date.timezone = Asia/Seoul
>>"%PHPINI%" echo opcache.enable = 1
>>"%PHPINI%" echo opcache.enable_cli = 0

if not exist "%DATA%\mysql" (
  echo [LEANTIME][INFO ] initializing MariaDB data dir ...
  "%MARIADB%\mariadb-install-db.exe" --datadir="%DATA%" > "%ROOT%\setup-mariadb-install.log" 2>&1
  if errorlevel 1 (
    echo [LEANTIME][ERROR] MariaDB data dir init failed. See "%ROOT%\setup-mariadb-install.log".
    goto :fail
  )
) else (
  echo [LEANTIME][INFO ] MariaDB data dir already initialized ^(skip^).
)

echo [LEANTIME][INFO ] starting MariaDB on 127.0.0.1:%LEANTIME_DB_PORT% ...
start "aeroone-leantime-mariadbd" "%MARIADB%\mariadbd.exe" --datadir="%DATA%" --port=%LEANTIME_DB_PORT% --skip-name-resolve --bind-address=127.0.0.1
call :wait_tcp %LEANTIME_DB_PORT% 30
if errorlevel 1 (
  echo [LEANTIME][ERROR] MariaDB did not start within 30s.
  goto :fail
)

echo [LEANTIME][INFO ] creating database + scoped user ...
set "SQLTMP=%TEMP%\aeroone_leantime_init_%RANDOM%.sql"
> "%SQLTMP%" echo CREATE DATABASE IF NOT EXISTS leantime CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
>>"%SQLTMP%" echo CREATE USER IF NOT EXISTS 'leantime'@'127.0.0.1' IDENTIFIED BY '%LEANTIME_DB_PASSWORD%';
>>"%SQLTMP%" echo CREATE USER IF NOT EXISTS 'leantime'@'localhost' IDENTIFIED BY '%LEANTIME_DB_PASSWORD%';
>>"%SQLTMP%" echo GRANT ALL PRIVILEGES ON leantime.* TO 'leantime'@'127.0.0.1';
>>"%SQLTMP%" echo GRANT ALL PRIVILEGES ON leantime.* TO 'leantime'@'localhost';
>>"%SQLTMP%" echo FLUSH PRIVILEGES;
"%MARIADB%\mariadb.exe" -u root --host=127.0.0.1 --port=%LEANTIME_DB_PORT% < "%SQLTMP%"
if errorlevel 1 (
  echo [LEANTIME][ERROR] database/user creation failed ^(see mariadb output above^).
  del /q "%SQLTMP%" >nul 2>&1
  goto :fail
)
del /q "%SQLTMP%" >nul 2>&1

echo [LEANTIME][INFO ] installing Leantime schema + first admin (non-interactive) ...
set "LEAN_DB_HOST=127.0.0.1"
set "LEAN_DB_USER=leantime"
set "LEAN_DB_PASSWORD=%LEANTIME_DB_PASSWORD%"
set "LEAN_DB_DATABASE=leantime"
set "LEAN_DB_PORT=%LEANTIME_DB_PORT%"
set "LEAN_USE_REDIS=false"
set "LEAN_NEWS_ENABLED=false"
set "LEAN_APP_URL=http://localhost:%LEANTIME_PORT%"
pushd "%ROOT%\leantime"
"%PHP%" -c "%PHPINI%" bin\leantime db:migrate -n --email="%LEANTIME_ADMIN_EMAIL%" --password="%LEANTIME_ADMIN_PASSWORD%" --company-name=AeroOne --first-name=Admin --last-name=User
set "LT_INSTALL_EXIT=%errorlevel%"
popd
if not "%LT_INSTALL_EXIT%"=="0" (
  echo [LEANTIME][WARN ] db:migrate returned %LT_INSTALL_EXIT%. If tables exist this may be a re-run; verify with start-leantime-stack.bat.
)

echo [LEANTIME][READY] setup complete. Admin: %LEANTIME_ADMIN_EMAIL%
echo [LEANTIME][INFO ] admin/DB credentials saved to leantime.env (this stack folder). Keep it private; do not share/commit.
echo [LEANTIME][INFO ] next: start-leantime-stack.bat  (serves http://localhost:%LEANTIME_PORT%)
if defined AEROONE_LT_INTERACTIVE pause
exit /b 0

:fail
echo [LEANTIME][ERROR] setup did not complete. Review the messages above.
if defined AEROONE_LT_INTERACTIVE pause
exit /b 1

:wait_tcp
REM %1 port, %2 timeout seconds
set "WT_PORT=%~1"
powershell -NoLogo -NoProfile -Command "$p=%WT_PORT%;$t=%~2;for($i=0;$i -lt $t;$i++){try{$c=New-Object Net.Sockets.TcpClient;$c.Connect('127.0.0.1',$p);$c.Close();exit 0}catch{Start-Sleep 1}};exit 1"
exit /b %errorlevel%
