"""Civil Aircraft 대시보드 v1.8 메타 번들 생성기.

포털(index.html) 첫 화면이 338KB 전체 데이터(civil-aircraft-data.*.js)를 받지 않고
KPI·분포 차트·검색만 즉시 그릴 수 있도록, 전체 데이터에서 경량 메타를 파생해
``assets/js/civil-aircraft-meta.v1.8.js`` (window.CIVIL_AIRCRAFT_META) 로 쓴다.

메타는 전체 데이터의 순수 파생물이므로 데이터가 바뀌면 이 스크립트를 다시 돌려
동기화한다. 회귀 테스트(test_civil_dashboard_bundle.py)가 이 파생을 재계산해
커밋된 메타와 정합을 강제한다 — 손으로 편집하면 테스트가 깨진다.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_BUNDLE = Path(__file__).resolve().parents[1] / 'app/modules/reports/civil_aircraft_dashboard'


def build_meta(data: dict[str, Any]) -> dict[str, Any]:
    aircraft = data['aircraft']
    grades = data.get('verificationGrades', {})

    category_counts: dict[str, int] = {}
    for a in aircraft:
        category_counts[a['category']] = category_counts.get(a['category'], 0) + 1
    category_dist = [
        {'label': label, 'value': value}
        for label, value in sorted(category_counts.items(), key=lambda kv: (-kv[1], kv[0]))
    ]

    order = ['A+', 'A', 'B+', 'B', 'C']
    grade_counts = {g: 0 for g in order}
    for a in aircraft:
        g = a['verificationGrade']
        grade_counts[g] = grade_counts.get(g, 0) + 1
    quality_dist = [
        {'label': g, 'sublabel': (grades.get(g) or {}).get('label', ''), 'value': grade_counts[g]}
        for g in order
    ]

    search_index = [
        {
            'id': a['id'],
            'model': a['model'],
            'manufacturer': a['manufacturer'],
            'family': a.get('family', ''),
            'aliases': a.get('aliases', []),
            'grade': a['verificationGrade'],
        }
        for a in aircraft
    ]

    complete = sum(1 for a in aircraft if a['verificationGrade'] in ('A+', 'A'))
    scale = sum(1 for a in aircraft if (a.get('dataQuality') or {}).get('hasScaleGeometry'))
    position = sum(1 for a in aircraft if (a.get('dataQuality') or {}).get('hasPositionData'))

    return {
        'version': '1.8',
        'counts': {
            'aircraftCount': len(aircraft),
            'sourceCount': len(data.get('sources', [])),
            'localPdfCount': data['metadata'].get('localPdfCount', len(data.get('localPdfArchive', []))),
            'completeCount': complete,
            'scaleCount': scale,
            'positionCount': position,
        },
        'categoryDist': category_dist,
        'qualityDist': quality_dist,
        'gradeDefs': {g: {'label': (grades.get(g) or {}).get('label', ''), 'definition': (grades.get(g) or {}).get('definition', '')} for g in order},
        'searchIndex': search_index,
    }


def render_meta_js(meta: dict[str, Any]) -> str:
    payload = json.dumps(meta, ensure_ascii=False, separators=(',', ':'), sort_keys=True)
    return (
        '// AUTO-GENERATED by backend/scripts/build_civil_meta.py — do not edit by hand.\n'
        '// 포털 첫 화면 경량 메타(KPI·분포·검색). 전체 데이터의 순수 파생물.\n'
        f'window.CIVIL_AIRCRAFT_META={payload};\n'
    )


def main() -> None:
    data_path = _BUNDLE / 'data/Civil_Aircraft_Data_v1.8.json'
    if not data_path.is_file():
        data_path = _BUNDLE / 'data/Civil_Aircraft_Data_v1.7.json'
    data = json.loads(data_path.read_text(encoding='utf-8'))
    meta = build_meta(data)
    out = _BUNDLE / 'assets/js/civil-aircraft-meta.v1.8.js'
    out.write_text(render_meta_js(meta), encoding='utf-8')
    print(f'wrote {out} ({out.stat().st_size} bytes, {len(meta["searchIndex"])} aircraft)')


if __name__ == '__main__':
    main()
